steps:
#First Clone from Google Cloud Source R 
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone','https://github.com/yarrabotula/hello-kubernetes.git']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/brilliant-scene-290913/hello-kubernetes2:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/brilliant-scene-290913/hello-kubernetes2' ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - delete
      - deployment
      - hello-kubernetes2
      - --ignore-not-found
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1
      - CLOUDSDK_CONTAINER_CLUSTER=kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - run
      - hello-kubernetes2
      - --image=gcr.io/brilliant-scene-290913/hello-kubernetes2
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1
      - CLOUDSDK_CONTAINER_CLUSTER=kubernetes
